# Generated by Django 2.0.1 on 2018-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn_app', '0002_auto_20180116_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesUnlikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('unlikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
        migrations.AddField(
            model_name='likesunlikes',
            name='post',
            field=models.ForeignKey(on_delete='on_delete', to='sn_app.Post'),
        ),
    ]
