# Generated by Django 2.0.1 on 2018-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn_app', '0003_auto_20180117_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesunlikes',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LikesUnlikes',
        ),
    ]
